//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLogging.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Log
    {
        public int LogID { get; set; }

        [StringLength(50)]
        [Display(Name = "First Name")]
        public string First_Name { get; set; }

        [StringLength(50)]
        [Display(Name = "Last Name")]
        public string Last_Name { get; set; }

        [StringLength(50)]
        [Display(Name = "Car Model")]
        public string Car_Model { get; set; }

        [Range(0, 10000)]
        [Display(Name = "Miles Driven")]
        public decimal Miles_Driven { get; set; }

        [Range(0, 1000)]
        [Display(Name = "Gallons Filled")]
        public decimal Gallons_Filled { get; set; }

        [Display(Name = "Fill Up Date & Time")]
        public System.DateTime Fill_Up_DateTime { get; set; }

        public Nullable<decimal> MPG { get; set; }


    }
}
